#pragma once
#define RAPIDJSON_MACROS_GET_TOC_MACRO(_0, _1, _2, _3, _4, _5, _6, _7, _8, NAME, ...) NAME

#define RAPIDJSON_MACROS_TOC_BOILERPLATE_1(name, ...) DESERIALIZE_ACTION(HandleTypes, if(false) int i##name{}; __VA_ARGS__ else throw JSONException("class " #name " could not deserialize into any of its type options"); )
#define RAPIDJSON_MACROS_TOC_BOILERPLATE_2(...) SERIALIZE_ACTION(HandleTypes, if(false) int i##name{}; __VA_ARGS__ )

#define RAPIDJSON_MACROS_TOC_INTERNAL_1(t) std::optional<t> t##_value = std::nullopt;
#define RAPIDJSON_MACROS_TOC_INTERNAL_2(t) else if(jsonValue.Is<t>()) self->t##_value = jsonValue.Get<t>();
#define RAPIDJSON_MACROS_TOC_INTERNAL_3(t) else if(self->t##_value.has_value()) jsonObject = rapidjson_macros_types::CreateJSONValue(self->t##_value.value(), allocator);
#define RAPIDJSON_MACROS_TOC_INTERNAL_4(name, t) name(t var) { t##_value = var; }

#define RAPIDJSON_MACROS_TOC_2(name, type1, type2) \
DECLARE_JSON_CLASS(name, \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type2) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_1(name, \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type2) \
    ) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_2( \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type2) \
    ) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type2) \
)

#define RAPIDJSON_MACROS_TOC_3(name, type1, type2, type3) \
DECLARE_JSON_CLASS(name, \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type3) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_1(name, \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type3) \
    ) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_2( \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type3) \
    ) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type3) \
)

#define RAPIDJSON_MACROS_TOC_4(name, type1, type2, type3, type4) \
DECLARE_JSON_CLASS(name, \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type4) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_1(name, \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type4) \
    ) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_2( \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type4) \
    ) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type4) \
)

#define RAPIDJSON_MACROS_TOC_5(name, type1, type2, type3, type4, type5) \
DECLARE_JSON_CLASS(name, \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type4) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type5) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_1(name, \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type4) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type5) \
    ) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_2( \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type4) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type5) \
    ) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type4) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type5) \
)

#define RAPIDJSON_MACROS_TOC_6(name, type1, type2, type3, type4, type5, type6) \
DECLARE_JSON_CLASS(name, \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type4) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type5) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type6) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_1(name, \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type4) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type5) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type6) \
    ) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_2( \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type4) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type5) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type6) \
    ) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type4) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type5) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type6) \
)

#define RAPIDJSON_MACROS_TOC_7(name, type1, type2, type3, type4, type5, type6, type7) \
DECLARE_JSON_CLASS(name, \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type4) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type5) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type6) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type7) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_1(name, \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type4) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type5) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type6) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type7) \
    ) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_2( \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type4) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type5) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type6) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type7) \
    ) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type4) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type5) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type6) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type7) \
)

#define RAPIDJSON_MACROS_TOC_8(name, type1, type2, type3, type4, type5, type6, type7, type8) \
DECLARE_JSON_CLASS(name, \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type4) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type5) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type6) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type7) \
    RAPIDJSON_MACROS_TOC_INTERNAL_1(type8) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_1(name, \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type4) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type5) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type6) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type7) \
        RAPIDJSON_MACROS_TOC_INTERNAL_2(type8) \
    ) \
    RAPIDJSON_MACROS_TOC_BOILERPLATE_2( \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type1) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type2) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type3) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type4) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type5) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type6) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type7) \
        RAPIDJSON_MACROS_TOC_INTERNAL_3(type8) \
    ) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type1) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type2) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type3) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type4) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type5) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type6) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type7) \
    RAPIDJSON_MACROS_TOC_INTERNAL_4(name, type8) \
)
